
#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNTCms.Web.Views.Shared.DisplayTemplates
{
    #line 2 "..\..\Views\Shared\DisplayTemplates\MenuHelperModel.cshtml"
#line default
    #line hidden
#line 3 "..\..\Views\Shared\DisplayTemplates\MenuHelperModel.cshtml"

#line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class _Views_Shared_DisplayTemplates_MenuHelperModel_cshtml : System.Web.WebPages.HelperPage
    {
    }
}
#pragma warning restore 1591
