using System.Linq;
using System.Web.Mvc.Html;
using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNTCms.Web.Views.Shared.DisplayTemplates
{
    #line 2 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
#line default
    #line hidden
#line 3 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"

#line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Shared/DisplayTemplates/SiteMapNodeModelList.cshtml")]
    public partial class _Views_Shared_DisplayTemplates_SiteMapNodeModelList_cshtml_ : System.Web.Mvc.WebViewPage<MvcSiteMapProvider.Web.Html.Models.SiteMapNodeModelList>
    {
        public _Views_Shared_DisplayTemplates_SiteMapNodeModelList_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n<ul>\n");

            
            #line 6 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
    
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
     foreach (var node in Model) { 

            
            #line default
            #line hidden
WriteLiteral("        <li>");

            
            #line 7 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
       Write(Html.DisplayFor(m => node));

            
            #line default
            #line hidden
WriteLiteral(" \n");

            
            #line 8 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
            
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
             if (node.Children.Any()) {
                
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
           Write(Html.DisplayFor(m => node.Children));

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
                                                    
            }

            
            #line default
            #line hidden
WriteLiteral("        </li>\n");

            
            #line 12 "..\..\Views\Shared\DisplayTemplates\SiteMapNodeModelList.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>");

        }
    }
}
#pragma warning restore 1591
