using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNTCms.Web.Views.Error
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Error/InternalServerError.cshtml")]
    public partial class _Views_Error_InternalServerError_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Error_InternalServerError_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Error\InternalServerError.cshtml"
  
    ViewBag.Title = "InternalServerError";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>InternalServerError</h2>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
