using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNTCms.Web.CodeTemplates.MvcFullDependencyCodeGenerator
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/CodeTemplates/MvcFullDependencyCodeGenerator/Error.cshtml")]
    public partial class _CodeTemplates_MvcFullDependencyCodeGenerator_Error_cshtml : System.Web.Mvc.WebViewPage<System.Web.Mvc.HandleErrorInfo>
    {
        public _CodeTemplates_MvcFullDependencyCodeGenerator_Error_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\CodeTemplates\MvcFullDependencyCodeGenerator\Error.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title>Error</title>\r\n</head>\r\n<body>\r\n    <hgroup>\r\n        <h1");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">Error.</h1>\r\n        <h2");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">An error occurred while processing your request.</h2>\r\n    </hgroup>\r\n</body>\r\n<" +
"/html>\r\n");

        }
    }
}
#pragma warning restore 1591
