using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNTCms.Web.Areas.Administrator.Views.Home
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Areas/Administrator/Views/Home/Index.cshtml")]
    public partial class _Areas_Administrator_Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Administrator_Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Administrator\Views\Home\Index.cshtml"
  
    ViewBag.Title = "";

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
