using System;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using System.Web.Optimization;
using System.Web.WebPages;
using DNTCms.Common.Constants;
using MvcSiteMapProvider.Web.Html;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNTCms.Web.Areas.Administrator.Views.Shared
{
    #line 1 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
#line default
    #line hidden
    
    #line 2 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
#line default
    #line hidden
    
    #line 3 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"

#line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Areas/Administrator/Views/Shared/_AdminLayout.cshtml")]
    public partial class _Areas_Administrator_Views_Shared__AdminLayout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Administrator_Views_Shared__AdminLayout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<!DOCTYPE html>\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n<html");

WriteLiteral(" class=\"no-js\"");

WriteLiteral(" lang=\"fa\"");

WriteLiteral(">\r\n<head>\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"content-language\"");

WriteLiteral(" content=\"fa\"");

WriteLiteral(" />\r\n    ");

WriteLiteral("\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(@">

    <!--[if lt IE 9]>
        <script src=""https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js""></script>
        <script src=""https://oss.maxcdn.com/respond/1.4.2/respond.min.js""></script>
    <![endif]-->
    <!--[if lte IE 6]>
        <script src=""/Scripts/warning.js""></script>
        <script>window.onload = function() { e(""js/ie6/""); }</script><![endif]-->
    <!--noscript-->
    <noscript>
        <meta");

WriteLiteral(" http-equiv=\"refresh\"");

WriteLiteral(" content=\"0;url=/NoScript.html\"");

WriteLiteral(">\r\n    </noscript>\r\n\r\n\r\n    ");

WriteLiteral("\r\n    <title>");

            
            #line 33 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 33 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
                       Write(Application.Name);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\r\n\r\n    ");

WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"57x57\"");

WriteLiteral(" href=\"/content/icons/apple-touch-icon-57x57.png\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"60x60\"");

WriteLiteral(" href=\"/content/icons/apple-touch-icon-60x60.png\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"72x72\"");

WriteLiteral(" href=\"/content/icons/apple-touch-icon-72x72.png\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"76x76\"");

WriteLiteral(" href=\"/content/icons/apple-touch-icon-76x76.png\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"114x114\"");

WriteLiteral(" href=\"/content/icons/apple-touch-icon-114x114.png\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"120x120\"");

WriteLiteral(" href=\"/content/icons/apple-touch-icon-120x120.png\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"144x144\"");

WriteLiteral(" href=\"/content/icons/apple-touch-icon-144x144.png\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"152x152\"");

WriteLiteral(" href=\"/content/icons/apple-touch-icon-152x152.png\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon\"");

WriteLiteral(" sizes=\"180x180\"");

WriteLiteral(" href=\"/content/icons/apple-touch-icon-180x180.png\"");

WriteLiteral(">\r\n\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/png\"");

WriteLiteral(" href=\"/content/icons/favicon-32x32.png\"");

WriteLiteral(" sizes=\"32x32\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/png\"");

WriteLiteral(" href=\"/content/icons/favicon-192x192.png\"");

WriteLiteral(" sizes=\"192x192\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/png\"");

WriteLiteral(" href=\"/content/icons/favicon-96x96.png\"");

WriteLiteral(" sizes=\"96x96\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/png\"");

WriteLiteral(" href=\"/content/icons/favicon-16x16.png\"");

WriteLiteral(" sizes=\"16x16\"");

WriteLiteral(">\r\n\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n    <meta");

WriteLiteral(" name=\"theme-color\"");

WriteLiteral(" content=\"#1E1E1E\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n\r\n\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 126 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
Write(Styles.Render("~/Admin/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <meta");

WriteLiteral(" name=\"x-font-awesome-stylesheet-fallback-test\"");

WriteLiteral(" class=\"fa\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 128 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
Write(Styles.Render("~/Content/fa"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 129 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
Write(System.Web.Optimization.Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 132 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
Write(RenderSection("head", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"navbar navbar-inverse \"");

WriteLiteral(" id=\"main-nav\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 10644), Tuple.Create("\"", 10680)
            
            #line 153 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
, Tuple.Create(Tuple.Create("", 10651), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Home.Index())
            
            #line default
            #line hidden
, 10651), false)
);

WriteLiteral("><img");

WriteLiteral(" alt=\"سامانه قضات\"");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" id=\"logo\"");

WriteAttribute("src", Tuple.Create(" src=\"", 10735), Tuple.Create("\"", 10782)
            
            #line 153 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
                                  , Tuple.Create(Tuple.Create("", 10741), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/Images/Logo.png")
            
            #line default
            #line hidden
, 10741), false)
);

WriteLiteral(" /></a>\r\n                <button");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-target=\"#navbar-main\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                </button>\r\n            </div>\r\n\r\n");

            
            #line 161 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
            
            
            #line default
            #line hidden
            
            #line 161 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
             if (User.Identity.IsAuthenticated)
            {
            
            
            #line default
            #line hidden
            
            #line 163 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
       Write(Html.Partial(MVC.Shared.Views._LoginPartial));

            
            #line default
            #line hidden
            
            #line 163 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
                                                         
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(@">
                <!--[if lt IE 8]>
                    <div class=""alert alert-warning"" role=""alert"">
                        <p>You are using an outdated browser. Please <a class=""alert-link"" href=""http://browsehappy.com/"">upgrade your browser</a> to improve your experience.</p>
                    </div>
                    <hr/>
                <![endif]-->

");

WriteLiteral("                ");

            
            #line 178 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
           Write(Html.MvcSiteMap().SiteMapPath(MVC.Shared.Views.DisplayTemplates.SiteMapPath));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n        <!-- Dialogs\r\n        ================================================" +
"== -->\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 187 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
            
            
            #line default
            #line hidden
            
            #line 187 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
             if (IsSectionDefined("Menu"))
            {

            
            #line default
            #line hidden
WriteLiteral("                <aside");

WriteLiteral(" class=\"col-md-2  animated fadeInRight\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"panel\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"list-group panel-body\"");

WriteLiteral(" id=\"sidebar\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 192 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
                       Write(RenderSection("Menu", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </a" +
"side>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"col-md-10  \"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 197 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
               Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 199 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"col-md-12 \"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 203 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
               Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 205 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"modal  fade in\"");

WriteLiteral(" id=\"modal\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 210 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
Write(System.Web.Optimization.Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 211 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
Write(System.Web.Optimization.Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 212 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
Write(System.Web.Optimization.Scripts.Render("~/bundles/jqueryvalunobtrusive"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 213 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
Write(System.Web.Optimization.Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 214 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
Write(System.Web.Optimization.Scripts.Render("~/bundles/site"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 215 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 216 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 216 "..\..\Areas\Administrator\Views\Shared\_AdminLayout.cshtml"
      Html.RenderPartial(MVC.Shared.Views._Noty);
            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
