using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNTCms.Web.Views.Account
{
    #line 2 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
#line default
    #line hidden
#line 3 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
#line default
    #line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Account/_ExternalLoginsListPartial.cshtml")]
    public partial class _Views_Account__ExternalLoginsListPartial_cshtml : System.Web.Mvc.WebViewPage<DNTCms.ViewModel.Account.ExternalLoginListViewModel>
    {
        public _Views_Account__ExternalLoginsListPartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
 if (Model.AuthenticationDescriptions!=null && Model.AuthenticationDescriptions.Any())
{
    using (Html.BeginForm(MVC.Account.ExternalLogin(), FormMethod.Post, htmlAttributes: new { @class = "form-horizontal", role = "form", id = "externalLoginForm", autocomplete = "off" }))
    {
        
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
   Write(Html.HiddenFor(m=>m.ReturnUrl));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
                                       
        foreach (var p in Model.AuthenticationDescriptions)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteAttribute("id", Tuple.Create(" id=\"", 640), Tuple.Create("\"", 666)
            
            #line 14 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
, Tuple.Create(Tuple.Create("", 645), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 645), false)
);

WriteLiteral("  onclick=\" AjaxForm.CustomSubmit(this, \'externalLoginForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-danger btn-block text-capitalize\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 15 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
               Write(p.AuthenticationType);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </button>\r\n            </div>\r\n");

            
            #line 18 "..\..\Views\Account\_ExternalLoginsListPartial.cshtml"
        }

    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
