using System;
using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNTCms.Web.Views.Account
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Account/ConfirmEmailPage.cshtml")]
    public partial class _Views_Account_ConfirmEmailPage_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Account_ConfirmEmailPage_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Account\ConfirmEmailPage.cshtml"
  
    ViewBag.Title = "شبیه سازی ایمیل";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row margin-top-5\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-10 col-md-offset-1\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                <h3");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">\r\n                    شبیه سازی فعال سازی اکانت\r\n                </h3>\r\n        " +
"    </div>\r\n            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                <hr/>\r\n                <i");

WriteLiteral(" class=\"fa fa-check text-success\"");

WriteLiteral("></i>\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 479), Tuple.Create("\"", 506)
            
            #line 16 "..\..\Views\Account\ConfirmEmailPage.cshtml"
, Tuple.Create(Tuple.Create("", 486), Tuple.Create<System.Object, System.Int32>(ViewBag.CallbackUrl
            
            #line default
            #line hidden
, 486), false)
);

WriteLiteral(">فعال سازی اکانت کاربری</a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</di" +
"v>");

        }
    }
}
#pragma warning restore 1591
