#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DNTCms.Common.Constants;
    using DNTCms.Common.Constants.HomeController;
    using DNTCms.Common.Extentions;
    using DNTCms.Common.OpenGraph;
    using DNTCms.Common.OpenGraph.ObjectTypes;
    using DNTCms.Common.Referrer;
    using DNTCms.Common.Twitter;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ConfirmEmail.cshtml")]
    public partial class _Views_Account_ConfirmEmail_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Account_ConfirmEmail_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Account\ConfirmEmail.cshtml"
  


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n        فعال سازی حساب کاربری\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n        <p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(">\r\n            با تشکر از عضویت شما در سایت. حساب شما با موفقیت فعال شد. برای ورو" +
"د به حساب خود کلیک کنید\r\n        </p>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\Account\ConfirmEmail.cshtml"
   Write(Html.ActionLink("ورود به حساب", MVC.Account.ActionNames.Login, MVC.Account.Name,
        routeValues: new { area = "" }, htmlAttributes: new { @class = "btn btn-block btn-md btn-success" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
