using System;
using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNTCms.Web.Views.Account
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Account/ForgotPasswordConfirmation.cshtml")]
    public partial class _Views_Account_ForgotPasswordConfirmation_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Account_ForgotPasswordConfirmation_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Account\ForgotPasswordConfirmation.cshtml"
  
   

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 6 "..\..\Views\Account\ForgotPasswordConfirmation.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n</hgroup>\r\n<div>\r\n    <p>\r\n        Please check your email to reset your " +
"password.\r\n    </p>\r\n    <p");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">\r\n        For DEMO only: You can click this link to reset password: <a");

WriteAttribute("href", Tuple.Create(" href=\"", 259), Tuple.Create("\"", 279)
            
            #line 13 "..\..\Views\Account\ForgotPasswordConfirmation.cshtml"
, Tuple.Create(Tuple.Create("", 266), Tuple.Create<System.Object, System.Int32>(ViewBag.Link
            
            #line default
            #line hidden
, 266), false)
);

WriteLiteral(">link</a>\r\n        Please change this code to register an email service in Identi" +
"tyConfig to send an email.\r\n    </p>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
