using System.Web.Mvc;
using System.Web.Mvc.Html;
using System.Web.WebPages;
using DNTCms.Common.HtmlHelpers;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNTCms.Web.Views.Account
{
    #line 3 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
#line default
    #line hidden
#line 4 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
#line default
    #line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Account/ReceiveActivatorEmail.cshtml")]
    public partial class _Views_Account_ReceiveActivatorEmail_cshtml : System.Web.Mvc.WebViewPage<DNTCms.ViewModel.Account.ActivationEmailViewModel>
    {
        public _Views_Account_ReceiveActivatorEmail_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
  


            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n");

            
            #line 11 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
     using (Html.BeginForm(MVC.Account.ActionNames.ReceiveActivatorEmail, MVC.Account.Name, null, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "receiveActivationEmailForm" ,autocomplete="off"}))
    {
        
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-md-10 col-md-offset-1\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel  panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n                    <strong> دریافت ایمیل فعال سازی</strong>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 21 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
                   Write(Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 23 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
                       Write(Html.NoAutoCompleteTextBoxForLtr(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 24 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n\r\n                 " +
"   ");

WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'receiveActivationEmailForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-success btn-block\"");

WriteLiteral(">\r\n                                دریافت ایمیل فعال سازی\r\n                      " +
"      </button>\r\n                        </div>\r\n\r\n                    </div>\r\n " +
"               </div>\r\n            </div>\r\n        </div>\r\n");

            
            #line 44 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 49 "..\..\Views\Account\ReceiveActivatorEmail.cshtml"
Write(System.Web.Optimization.Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
