#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Account\Register.cshtml"
    using CaptchaMvc.HtmlHelpers;
    
    #line default
    #line hidden
    using DNTCms.Common.Constants;
    using DNTCms.Common.Constants.HomeController;
    using DNTCms.Common.Extentions;
    
    #line 3 "..\..\Views\Account\Register.cshtml"
    using DNTCms.Common.HtmlHelpers;
    
    #line default
    #line hidden
    using DNTCms.Common.OpenGraph;
    using DNTCms.Common.OpenGraph.ObjectTypes;
    using DNTCms.Common.Referrer;
    using DNTCms.Common.Twitter;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Register.cshtml")]
    public partial class _Views_Account_Register_cshtml : System.Web.Mvc.WebViewPage<DNTCms.ViewModel.Account.RegisterViewModel>
    {
        public _Views_Account_Register_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Account\Register.cshtml"
  


            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\r\n");

            
            #line 10 "..\..\Views\Account\Register.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Account\Register.cshtml"
     using (Html.BeginForm(MVC.Account.ActionNames.Register, MVC.Account.Name, FormMethod.Post,
                new { id = "registerForm", area = "", @class = "form-horizontal", role = "form", autocomplete = "off" }))
    {
        
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\Register.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\Register.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-md-10 col-md-offset-1\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 17 "..\..\Views\Account\Register.cshtml"
               Write(Html.HelpAlert(Url.Content("~/Content/Images/lightbulb.png"),
                    "کاربر گرامی بعد از ثبت نام در سیستم  خواهید توانست به دوستان یا آشنایان خود که در ای سیستم عضو هستند ، دعوت نامه بفرستید.",
                    "دقت کنید شماره همراه شما یا ایمیلی که وارد میکنید ، به عنوان نام کاربری شما در نظر گرفته خواهد شد"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 23 "..\..\Views\Account\Register.cshtml"
                   Write(Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 25 "..\..\Views\Account\Register.cshtml"
                       Write(Html.NoAutoCompleteTextBoxForLtr(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 26 "..\..\Views\Account\Register.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n\r\n                 " +
"   <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 31 "..\..\Views\Account\Register.cshtml"
                   Write(Html.LabelFor(m => m.NameForShow, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 33 "..\..\Views\Account\Register.cshtml"
                       Write(Html.NoAutoCompleteTextBoxFor(m => m.NameForShow));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 34 "..\..\Views\Account\Register.cshtml"
                       Write(Html.ValidationMessageFor(m => m.NameForShow, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 38 "..\..\Views\Account\Register.cshtml"
                   Write(Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 40 "..\..\Views\Account\Register.cshtml"
                       Write(Html.FormControlPasswordFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 41 "..\..\Views\Account\Register.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 45 "..\..\Views\Account\Register.cshtml"
                   Write(Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 47 "..\..\Views\Account\Register.cshtml"
                       Write(Html.FormControlPasswordFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 48 "..\..\Views\Account\Register.cshtml"
                       Write(Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n\r\n                 " +
"   <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 53 "..\..\Views\Account\Register.cshtml"
                   Write(Html.MathCaptcha(MVC.Shared.Views._CaptchaPartial));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\"AjaxForm.CustomSubmit(this, \'registerForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-success btn-block\"");

WriteLiteral(">\r\n                                تأیید اطلاعات برای تکمیل عضویت\r\n              " +
"              </button>\r\n                        </div>\r\n                    </d" +
"iv>\r\n                </div>\r\n            </div>\r\n        </div>\r\n");

            
            #line 67 "..\..\Views\Account\Register.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 71 "..\..\Views\Account\Register.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
