using System.Web.Mvc;
using System.Web.Mvc.Html;
using System.Web.WebPages;
using DNTCms.Common.HtmlHelpers;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNTCms.Web.Views.Account
{
    #line 2 "..\..\Views\Account\UploadAvatar.cshtml"
#line default
    #line hidden
#line 3 "..\..\Views\Account\UploadAvatar.cshtml"
#line default
    #line hidden
    
    #line 4 "..\..\Views\Account\UploadAvatar.cshtml"
#line default
    #line hidden
    
    #line 5 "..\..\Views\Account\UploadAvatar.cshtml"
#line default
    #line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Account/UploadAvatar.cshtml")]
    public partial class _Views_Account_UploadAvatar_cshtml : System.Web.Mvc.WebViewPage<DNTCms.ViewModel.Account.ChangeAvatarViewModel>
    {
        public _Views_Account_UploadAvatar_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\Account\UploadAvatar.cshtml"
  
    ViewBag.Title = "تغییر تصویر کاربری";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row margin-top-5\"");

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Views\Account\UploadAvatar.cshtml"
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Account\UploadAvatar.cshtml"
     using (Html.BeginForm(MVC.Account.UploadAvatar(), FormMethod.Post, htmlAttributes: new { @class = "form-horizontal", role = "form", id = "avatarForm", autocomplete = "off", enctype = "multipart/form-data" }))
    {
        
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\UploadAvatar.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\UploadAvatar.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"col-md-2\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Views\Account\UploadAvatar.cshtml"
       Write(Html.Image((byte[])ViewBag.Avatar, "تصویر کاربری", "img-rounded img-responsive img-thumbnail", 130));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel  panel-default\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 20 "..\..\Views\Account\UploadAvatar.cshtml"
               Write(Html.HelpAlert(Url.Content("~/Content/Images/lightbulb.png"),
                        "کاربر گرامی از این قسمت برای تغییر تصویر کاربری خود استفاده کنید",
                        "لطفا از فایل های png-jpg-gif-jpeg فقط استفاده کنید", "به صورت پیش فرض ، تصویری برای شما در نظر گرفته شده است"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 26 "..\..\Views\Account\UploadAvatar.cshtml"
                   Write(Html.TextBoxFor(model => model.Avatar, new { type = "file", @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"panel-footer\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onclick=\" AjaxForm.CustomSubmit(this, \'avatarForm\')\"");

WriteLiteral(" data-loading-text=\"در حال ارسال اطلاعات\"");

WriteLiteral(" class=\"btn btn-success btn-block\"");

WriteLiteral(">\r\n                        ارسال به سرور\r\n                    </button>\r\n        " +
"        </div>\r\n            </div>\r\n        </div>\r\n");

            
            #line 36 "..\..\Views\Account\UploadAvatar.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 39 "..\..\Views\Account\UploadAvatar.cshtml"
Write(System.Web.Optimization.Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
