using System.Web.Mvc.Html;
using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNTCms.Web.Views.Shared.EditorTemplates
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Shared/EditorTemplates/Enum.cshtml")]
    public partial class _Views_Shared_EditorTemplates_Enum_cshtml_ : System.Web.Mvc.WebViewPage<System.Enum>
    {
        public _Views_Shared_EditorTemplates_Enum_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\EditorTemplates\Enum.cshtml"
Write(EnumHelper.IsValidForEnumHelper(ViewData.ModelMetadata) ?
Html.EnumDropDownListFor(model => model, htmlAttributes: new { @class = "form-control input-sm" }) 
: Html.TextBoxFor(model => model, htmlAttributes: new { @class = "form-control" }));

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
