using System.Web.WebPages;
using DNTCms.Utility;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNTCms.Web.Views.Shared
{
    #line 1 "..\..\Views\Shared\_AuditLog.cshtml"
#line default
    #line hidden
#line 2 "..\..\Views\Shared\_AuditLog.cshtml"
#line default
    #line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Shared/_AuditLog.cshtml")]
    public partial class _Views_Shared__AuditLog_cshtml : System.Web.Mvc.WebViewPage<DNTCms.ViewModel.Common.BaseViewModel>
    {
        public _Views_Shared__AuditLog_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<hr");

WriteLiteral(" class=\"margin-bottom-5 margin-top-5\"");

WriteLiteral(">\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"fa fa-calendar-o\"");

WriteLiteral("></i>\r\n        <small>ثبت شده در :</small>\r\n        <time>");

            
            #line 9 "..\..\Views\Shared\_AuditLog.cshtml"
         Write(Model.CreateDate.ToPersianString(PersianDateTimeFormat.Date));

            
            #line default
            #line hidden
WriteLiteral("</time>\r\n        <i");

WriteLiteral(" class=\"fa fa-clock-o \"");

WriteLiteral("></i>\r\n        <time>");

            
            #line 11 "..\..\Views\Shared\_AuditLog.cshtml"
         Write(Model.CreateDate.ToPersianTimeString());

            
            #line default
            #line hidden
WriteLiteral("</time>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
