#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Shared\_LoginPartial.cshtml"
    using Auth = DNTCms.ServiceLayer.Security.AssignableToRolePermissions;
    
    #line default
    #line hidden
    using DNTCms.Common.Constants;
    using DNTCms.Common.Constants.HomeController;
    using DNTCms.Common.Extentions;
    using DNTCms.Common.OpenGraph;
    using DNTCms.Common.OpenGraph.ObjectTypes;
    using DNTCms.Common.Referrer;
    using DNTCms.Common.Twitter;
    
    #line 2 "..\..\Views\Shared\_LoginPartial.cshtml"
    using DNTCms.ServiceLayer.Security;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_LoginPartial.cshtml"
    using DNTCms.Web.HtmlHelpers;
    
    #line default
    #line hidden
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LoginPartial.cshtml")]
    public partial class _Views_Shared__LoginPartial_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__LoginPartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(" id=\"navbar-main\"");

WriteLiteral(">\r\n    <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n\r\n");

            
            #line 8 "..\..\Views\Shared\_LoginPartial.cshtml"
        
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Shared\_LoginPartial.cshtml"
         if (Context.User.IsInRole(Auth.CanManageUser))
        {

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" class=\"main\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n            </li>\r\n");

WriteLiteral("            <li");

WriteLiteral(" class=\"main\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 14 "..\..\Views\Shared\_LoginPartial.cshtml"
           Write(Html.SecureActionLink("لاگ سیستم", MVC.Administrator.Elmah.Index()));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </li>\r\n");

            
            #line 16 "..\..\Views\Shared\_LoginPartial.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    </ul>\r\n    <ul");

WriteLiteral(" class=\"nav navbar-nav navbar-left\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Views\Shared\_LoginPartial.cshtml"
        
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Shared\_LoginPartial.cshtml"
         if (Context.User.IsInRole(StandardRoles.Administrators))
        {

            
            #line default
            #line hidden
WriteLiteral("            <li");

WriteLiteral(" class=\"dropdown noti-dropdown main\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"badge bage-noti digit\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"fa fa-warning  animated infinite fadeIn\"");

WriteLiteral("></span>\r\n                    قرار های امروز\r\n                </a>\r\n            <" +
"/li>\r\n");

            
            #line 29 "..\..\Views\Shared\_LoginPartial.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <li>\r\n            <div");

WriteLiteral(" id=\"dl-menu\"");

WriteLiteral(" class=\"dl-menuwrapper\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"dl-trigger\"");

WriteLiteral("></button>\r\n                <ul");

WriteLiteral(" class=\"dl-menu\"");

WriteLiteral(">\r\n                    <li>\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1263), Tuple.Create("\"", 1309)
            
            #line 36 "..\..\Views\Shared\_LoginPartial.cshtml"
, Tuple.Create(Tuple.Create("", 1270), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Account.UploadAvatar())
            
            #line default
            #line hidden
, 1270), false)
);

WriteLiteral(">\r\n                            ویرایش تصویر کاربری\r\n                        </a>\r" +
"\n                    </li>\r\n");

            
            #line 40 "..\..\Views\Shared\_LoginPartial.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\Shared\_LoginPartial.cshtml"
                     if (Context.User.IsInRole(StandardRoles.Administrators))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                ملاقات ها\r\n                                <sp" +
"an");

WriteLiteral(" class=\"fa fa-caret-left pull-left\"");

WriteLiteral("></span>\r\n                            </a>\r\n\r\n                            <ul");

WriteLiteral(" class=\"dl-submenu\"");

WriteLiteral(">\r\n                                  </ul>\r\n                            \r\n       " +
"                 </li>\r\n");

            
            #line 52 "..\..\Views\Shared\_LoginPartial.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n");

            
            #line 54 "..\..\Views\Shared\_LoginPartial.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\Shared\_LoginPartial.cshtml"
                         using (Html.BeginForm(MVC.Account.LogOff(), FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                        {
                            
            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Shared\_LoginPartial.cshtml"
                       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Shared\_LoginPartial.cshtml"
                                                    


            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteLiteral(" href=\"javascript:document.getElementById(\'logoutForm\').submit()\"");

WriteLiteral(">خروج</a>\r\n");

            
            #line 59 "..\..\Views\Shared\_LoginPartial.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </li>\r\n\r\n\r\n                </ul>\r\n            </div>\r\n       " +
"     <!-- /dl-menuwrapper -->\r\n        </li>\r\n    </ul>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
