using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNTCms.Web.Views.Shared
{
    #line 1 "..\..\Views\Shared\_UserProfileSideBarMenu.cshtml"
#line default
    #line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Shared/_UserProfileSideBarMenu.cshtml")]
    public partial class _Views_Shared__UserProfileSideBarMenu_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__UserProfileSideBarMenu_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"list-group-item\"");

WriteLiteral("><span");

WriteLiteral(" class=\"fa fa-cogs\"");

WriteLiteral("></span>تنظیمات کاربری</a>\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");

        }
    }
}
#pragma warning restore 1591
